---
# Configuration: https://r-pufky.github.io/docs/service/mkdocs
#
# uv run mkdocs serve --livereload
# uv run mkdocs gh-deploy

###############################################################################
# Page Configuration
###############################################################################
site_name: 'Docs: A Collection of Notes'
repo_url: 'https://github.com/r-pufky/docs'
site_url: 'https://github.com/r-pufky/docs'
edit_uri: 'edit/main/docs'
site_author: 'r-pufky'
copyright: '©2025'
remote_branch: 'gh-pages'
remote_name: 'origin'

nav:
  - 'README.md'
  # General apps place native spot. Combined apps go in root app.
  - 'Applications':
    - 'CLI':
      - 'app/cli/app_bundles.md'
      - 'app/cli/bash.md'
      - 'app/cli/direnv.md'
      - 'app/cli/fish.md'
      - 'app/cli/video_tools.md'
      - 'Vim':
        - 'app/cli/vim/README.md'
        - 'app/cli/vim/troubleshooting.md'
      - 'app/cli/yt_dlp.md'
    - 'GUI':
      - 'app/gui/chrome.md'
      - 'app/gui/firefox.md'
      - 'app/gui/freecad.md'
      - 'app/gui/movie_studio.md'
      - 'app/gui/putty.md'
      - 'VSCode':
        - 'app/gui/vscode/README.md'
        - 'app/gui/vscode/code_server.md'
        - 'app/gui/vscode/troubleshooting.md'
    - 'WebUI':
      - 'app/webui/selkies.md'
    - 'GPG with Yubikey':
      - 'app/gpg/README.md'
      - 'Setup':
        - 'app/gpg/setup/README.md'
        - 'app/gpg/setup/master.md'
        - 'app/gpg/setup/subkey.md'
        - 'app/gpg/setup/backup.md'
        - 'app/gpg/setup/export_to_yubikey.md'
        - 'app/gpg/setup/cleanup.md'
        - 'app/gpg/setup/import.md'
      - 'OS':
        - 'app/gpg/os/linux.md'
        - 'app/gpg/os/windows.md'
      - 'app/gpg/operations.md'
      - 'app/gpg/troubleshooting.md'
  - 'Databases':
    - 'db/mariadb.md'
    - 'PostgresQL':
      - 'db/postgres/README.md'
      - 'db/postgres/troubleshooting.md'
  - 'Filesystems':
    - 'NFS':
      - 'filesystem/nfs/README.md'
      - 'filesystem/nfs/exports.md'
      - 'filesystem/nfs/mounts.md'
      - 'filesystem/nfs/optimizations.md'
      - 'filesystem/nfs/options.md'
      - 'filesystem/nfs/troubleshooting.md'
    - 'ZFS':
      - 'filesystem/zfs/README.md'
      - 'filesystem/zfs/sync_backup.md'
      - 'filesystem/zfs/replacing_disks.md'
      - 'filesystem/zfs/encryption.md'
    - 'filesystem/copying_data.md'
    - 'filesystem/wiping_data.md'
  - 'Hardware':
    - 'hardware/amt.md'
    - 'hardware/bnk9.md'
    - 'hardware/crush_80_reboot_pro.md'
    - 'Secure Boot':
      - 'hardware/secure_boot/README.md'
      - 'hardware/secure_boot/troubleshooting.md'
  - 'Games':
    - 'Ludusavi':
      - 'game/ludusavi/README.md'
    - 'game/conan_exiles.md'
    - 'game/elden_ring.md'
    - 'Escape from Tarkov':
      - 'game/escape_from_tarkov/README.md'
      - 'game/escape_from_tarkov/server.md'
    - 'game/mumble/mumble.md'
    - 'Seven Days to Die':
      - 'game/seven_days_to_die/README.md'
      - 'game/seven_days_to_die/serverconfig.md'
      - 'game/seven_days_to_die/serveradmin.md'
    - 'game/star_rupture.md'
    - 'Steam':
      - 'game/steam/README.md'
      - 'game/steam/troubleshooting.md'
  - 'Mail':
    - 'mail/imapsync.md'
    - 'Mox':
      - 'mail/mox/README.md'
      - 'mail/mox/troubleshooting.md'
    - 'mail/mutt.md'
    - 'mail/postfix.md'
    - 'mail/roundcube.md'
  - 'Media Management':
    # - 'media/folders.md'
    - 'media/deluge.md'
    - 'media/lidarr.md'
    - 'media/music.md'
    - 'media/nzbget.md'
    - 'Paperless':
      - 'media/paperless/README.md'
      - 'media/paperless/troubleshooting.md'
    - 'media/playon.md'
    - 'Plex':
      - 'media/plex/README.md'
      - 'media/plex/config.md'
      - 'media/plex/troubleshooting.md'
    - 'Radarr':
      - 'media/radarr/README.md'
      - 'media/radarr/troubleshooting.md'
    - 'Sonarr':
      - 'media/sonarr/README.md'
      - 'media/sonarr/troubleshooting.md'
  - 'Networking':
    - 'Dropbear':
      - 'network/dropbear/README.md'
      - 'network/dropbear/troubleshooting.md'
    - 'network/pihole.md'
    - 'Traefik':
      - 'network/traefik/README.md'
      - 'network/traefik/basic_auth_dashboard.md'
      - 'network/traefik/error_pages.md'
      - 'network/traefik/rate_limiting.md'
      - 'network/traefik/plugins.md'
      - 'ACME Certificates':
        - 'network/traefik/acme/README.md'
        - 'network/traefik/acme/behind_traefik.md'
      - 'network/traefik/odic.md'
      - 'network/traefik/troubleshooting.md'
    - 'UniFi':
      - 'network/unifi/README.md'
      - 'network/unifi/troubleshooting.md'
    - 'network/vlan.md'
    - 'SSH':
      - 'network/ssh/README.md'
      - 'SSHD':
        - 'network/ssh/sshd/linux.md'
        - 'network/ssh/sshd/windows.md'
      - 'network/ssh/troubleshooting.md'
    - 'Wireguard':
      - 'network/wireguard/README.md'
      - 'OS':
        - 'network/wireguard/os/linux.md'
        - 'network/wireguard/os/windows.md'
      - 'network/wireguard/troubleshooting.md'
  - 'Operating Systems':
    - 'CachyOS':
      - 'os/cachyos/README.md'
      - 'os/cachyos/preferences.md'
      - 'os/cachyos/troubleshooting.md'
    - 'Debian':
      - 'os/debian/README.md'
      - 'os/debian/troubleshooting.md'
    - 'os/kindle.md'
    - 'os/pikvm.md'
    - 'Proxmox (PVE)':
      - 'os/pve/README.md'
      - 'os/pve/acme.md'
      - 'os/pve/audio.md'
      - 'os/pve/gpu.md'
      - 'os/pve/nfs.md'
      - 'os/pve/troubleshooting.md'
    - 'os/shield.md'
    - 'os/web_os.md'
    - 'Windows':
      - 'os/windows/README.md'
      - 'os/windows/reinstall.md'
      - 'os/windows/crashes.md'
      - 'os/windows/troubleshooting.md'
  - 'Printing':
    - 'printing/linux.md'
    - 'printing/windows.md'
    - 'printing/brother_mfcl2750dw.md'
  - 'Services':
    - 'service/README.md'
    - 'service/bluebubbles.md'
    - 'Certificate Authority':
      - 'service/ca/README.md'
      - 'service/ca/setup.md'
      - 'service/ca/certificates.md'
      - 'service/ca/certificate_revocation_list.md'
    - 'service/mkdocs.md'
    - 'NGINX':
      - 'service/nginx/README.md'
      - 'Manual Configuration':
        - 'service/nginx/manual/README.md'
        - 'service/nginx/manual/setup.md'
        - 'service/nginx/manual/custom_error_pages.md'
        - 'service/nginx/manual/cert_based_authentication.md'
        - 'service/nginx/manual/best_practices.md'
      - 'service/nginx/troubleshooting.md'
    - 'service/systemd.md'
  - 'Version Control':
    - 'Forgejo':
      - 'vcs/forgejo/README.md'
      - 'vcs/forgejo/troubleshooting.md'
    - 'GIT':
      - 'vcs/git/README.md'
      - 'vcs/git/branches.md'
      - 'vcs/git/troubleshooting.md'
  - 'Glossary':
    - 'glossary/README.md'
    - 'glossary/admonitions.md'
    - 'glossary/gpg.md'
    - 'glossary/mail.md'
    - 'glossary/os.md'
    - 'glossary/unicode.md'
    - 'glossary/vlan.md'
    - 'glossary/yubikey.md'

extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/r-pufky'
    - icon: 'simple/gnuprivacyguard'
      link: 'https://keys.openpgp.org/vks/v1/by-fingerprint/466EEC2B67516C7117C85CE3A0BC35D16698BAB9'

theme:
  name: 'material'
  palette:
    - media: '(prefers-color-scheme)'
      toggle:
        icon: 'material/link'
        name: 'Switch to light mode'
    - media: '(prefers-color-scheme: light)'
      scheme: 'default'
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: 'material/toggle-switch'
        name: 'Switch to dark mode'
    - media: '(prefers-color-scheme: dark)'
      scheme: 'slate'
      primary: 'black'
      accent: 'indigo'
      toggle:
        icon: 'material/toggle-switch-off'
        name: 'Switch to system preference'
  icon:
    annotation: 'material/chevron-right-circle'
  features:
    - 'navigation.instant'
    - 'navigation.instant.prefetch'
    - 'navigation.instant.progress'
    - 'navigation.tracking'
    - 'navigation.path'
    - 'navigation.indexes'
    - 'navigation.top'
    - 'search.suggest'
    - 'search.highlight'
    - 'toc.follow'
    - 'header.autohide'
    - 'content.action.edit'
    - 'content.footnote.tooltips'
  navigation_depth: 5
  locale: 'en'
  language: 'en'

markdown_extensions:
  - 'attr_list'
  - 'def_list'
  - 'footnotes'
  - 'md_in_html'
  - 'tables'
  - 'pymdownx.betterem'
  - 'pymdownx.magiclink'
  - 'pymdownx.superfences'
  - 'admonition'
  - 'pymdownx.details'
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: 'lower'
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      use_pygments: false
  - 'pymdownx.inlinehilite'

plugins:
  - 'glightbox'
  - git-revision-date-localized:
      enable_creation_date: true
  - 'search'

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/highlight.min.js'
  - 'https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js'
  - '_material/init.js'

extra_css:
  - 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/styles/vs2015.min.css'
