---
###############################################################################
# Ports Configuration
###############################################################################
# Ports should be managed externally via an OS role.
#
# Reference:
# * https://docs.ansible.com/ansible/latest/collections/community/general/ufw_module.html

ports:
  - {proto: 'tcp', from_ip: 'any',       to_port: 7878, direction: 'in', comment: 'radarr http'}
  - {proto: 'tcp', from_ip: '127.0.0.1', to_port: 7878, direction: 'in', comment: 'radarr http api'}
  - {proto: 'tcp', from_ip: 'any',       to_port: 9898, direction: 'in', comment: 'radarr https'}
  - {proto: 'tcp', from_ip: '127.0.0.1', to_port: 9898, direction: 'in', comment: 'radarr https api'}