---
###############################################################################
# Ports Configuration
###############################################################################
# Ports should be managed externally via an OS role.
#
# Conan Exiles dedicate server no longer uses steam for discovery, but keeps
# the port for backwards compatibility for server queries.
#
# Reference:
# * https://www.conanexiles.com/dedicated-servers/
# * https://conanexiles.fandom.com/wiki/Dedicated_Server_Setup:_Linux_and_Wine
# * https://r-pufky.github.io/docs/game/conan/index.html
# * https://forums.funcom.com/t/hosting-a-dedicated-server-for-isle-of-siptah/136857/4

ports:
  - {proto: 'udp', from_ip: 'any', to_port: 7777,  direction: 'in', comment: 'conan exiles main game connections'}
  - {proto: 'udp', from_ip: 'any', to_port: 7778,  direction: 'in', comment: 'conan exiles ping port for server browser (always main port +1)'}
  - {proto: 'udp', from_ip: 'any', to_port: 27015, direction: 'in', comment: 'conan exiles server query port'}
  - {proto: 'tcp', from_ip: 'any', to_port: 7777,  direction: 'in', comment: 'conan exiles mod transfers to clients'}
  - {proto: 'tcp', from_ip: 'any', to_port: 25575, direction: 'in', comment: 'conan exiles remote administration (rcon)'}