---
###############################################################################
# Left 4 Dead (+9GB)
###############################################################################

# Install preconfigured L4D server?
steam_l4d_enable: false

# Root install location.
steam_l4d_dir: '/home/steam/l4d'

# Additional steamcmd options to use during app_update. Default: ''.
steam_l4d_app_extras: ''

# Update steamcmd. Default: true.
steam_l4d_update_steamcmd: true

# Update L4D2 server. Default: true.
steam_l4d_update_server: true

# Target location of sourcemod install tarball on ansible host. Empty disables.
#
# Reference:
# * https://www.sourcemod.net/
steam_l4d_sourcemod: 'host_vars/data/sourcemod-1.10.0-git6510-linux.tar.gz'

# Target location of metamod install tarball on ansible host. Empty disables.
#
# Reference:
# * http://www.sourcemm.net/
steam_l4d_metamod: 'host_vars/data/mmsource-1.11.0-git1145-linux.tar.gz'

###############################################################################
# Host Message (host.txt)
###############################################################################
# Contents for the HOST file. Generally these are very finicky and
# mis-documented throughout the web. Use plain text or use a single line
# pointing to a **HTTP** only link, which will render the MOTD banner.
#
# Reference:
# * http://www.custwiki.cyberwurx.com/index.php/Using_host.txt_for_a_Server_Banner

steam_l4d_host: ''

###############################################################################
# Message of the Day (motd.txt)
###############################################################################
# Contents for the MOTD file. Generally these are very finicky and
# mis-documented throughout the web. Prefer plain text or use a single line
# pointing to a **HTTP** only link, which will render the MOTD banner.
#
# Reference:
# * http://www.custwiki.cyberwurx.com/index.php/Using_host.txt_for_a_Server_Banner

steam_l4d_motd: ''

###############################################################################
# Server Configuration (server.cfg)
###############################################################################

steam_l4d_server:
  # Server
  hostname:                    'L4D Server'
  sv_password:                 ''
  sv_allow_lobby_connect_only: 0
  sv_steamgroup:               0
  sv_steamgroup_exclusive:     0
  sv_search_key:               'L4D Server'
  sv_gametypes:                'coop,survival,versus,teamversus'
  rcon_password:               ''
  sv_rcon_banpenalty:          360
  sv_rcon_log:                 1
  sv_rcon_maxfailures:         3
  sv_rcon_minfailuretime:      600

  # General: Play
  motd_enabled:          1
  mp_disable_autokick:   1
  sv_allow_wait_command: 0
  sv_allowdownload:      0
  sv_allowupload:        0
  sv_alltalk:            0
  sv_alternateticks:     0
  sv_cheats:             0
  sv_consistency:        1
  sv_contact:            ''
  sv_downloadurl:        ''
  sv_pausable:           1
  sv_lan:                1
  sv_region:             1

  # Rate: settings
  # Min bandwidth rate allowed on: server
  sv_minrate:    40000
  # Max bandwidth rate allowed on: server
  sv_maxrate:    50000
  # Minimum cmd rate (match server: tickrate)
  sv_mincmdrate: 0
  # Minimum cmd rate (match server: tickrate)
  sv_maxcmdrate: 67

  # Server: Logging
  sv_log_onefile: 0
  sv_logbans:     1
  sv_logecho:     1
  sv_logfile:     1
  # log to disk on each write (slow)
  sv_logflush:    0
  # logs folder relative to game directory
  sv_logsdir:     'logs'

###############################################################################
# Sourcemod Simple Admins (admins_simple.ini)
###############################################################################
# Simple admin privleges through Steam ID mamangement. Anymore more complicated
# requires manual management of files. Only applied if not empty and sourcemod
# is enabled. See references for formats.
#
# steam_l4d_admins: [{user: 'STEAMID', priv: 'PRIV STRING'}]
#
# Reference:
# * https://wiki.alliedmods.net/Adding_Admins_(SourceMod)
# * https://www.steamidfinder.com/

steam_l4d_admins: []
