#!/bin/bash
#
# Mounts a given image for TFTP serving
#

if [ $# -ne 1 ]; then
  echo "Usage: mount-tftp-image <IMAGE>.iso"
  exit 0
fi

sudo mount -o loop ${1} /media/cdrom
sudo mount --bind /media/cdrom/install/netboot/ /var/lib/tftpboot/
sudo service tftpd-hpa restart
