---
###############################################################################
# Ports Configuration
###############################################################################
# Ports should be managed externally via an OS role.
#
# Reference:
# * https://docs.ansible.com/ansible/latest/collections/community/general/ufw_module.html

ports:
  - {proto: 'tcp', from_ip: 'any', to_port: 8112, direction: 'in',  comment: 'deluge http'}
  - {proto: 'tcp', from_ip: 'any', to_port: 8080, direction: 'in',  comment: 'deluge socks proxy'}
  - {proto: 'tcp', from_ip: 'any', to_port: 6881, direction: 'in',  comment: 'deluge inbound torrent service'}
  - {proto: 'udp', from_ip: 'any', to_port: 6881, direction: 'in',  comment: 'deluge inbound torrent service'}
  - {proto: 'tcp', from_ip: 'any', to_port: 6891, direction: 'in',  comment: 'deluge inbound torrent service'}
  - {proto: 'udp', from_ip: 'any', to_port: 6891, direction: 'in',  comment: 'deluge inbound torrent service'}
  - {proto: 'tcp', to_ip: 'any',   to_port: 0,    direction: 'out', comment: 'deluge outbound torrent service'}
  - {proto: 'udp', to_ip: 'any',   to_port: 0,    direction: 'out', comment: 'deluge outbound torrent service'}
