#!/bin/bash
#
# Runs as root. Drop privileges.
#
# Capture kill/term signals and send SIGINT to gracefully shutdown 7days server.
PROCESS_WAIT_TIME=25
WATCHDOG_TIME=300

function shutdown() {
  echo 'Shutting down server ...'
  if [ "$(pgrep -n 7Days)" != '' ]; then
    echo "Sending SIGQUIT to 7 Days server (max ${PROCESS_WAIT_TIME} secs) ..."
    kill -SIGQUIT `pgrep -n 7Days`
    sleep ${PROCESS_WAIT_TIME}
  fi
  exit 0
}
trap shutdown SIGINT SIGKILL SIGTERM

function start_server() {
  su steam -c "/data/server/startserver.sh -configfile=/data/server/serverconfig.xml"
}

function watch_server() {
  if ps aux | grep [7]DaysToDieServer > /dev/null; then
    echo 'Server is running ...'
  else
    echo 'Starting server ...'
    start_server &
  fi
}

while true; do
  watch_server
  # background and using wait enables trap capture.
  sleep ${WATCHDOG_TIME} &
  wait
done
