---
###############################################################################
# Git Wrapper
###############################################################################
# Light-weight wrapper to pre-configure machine for ansible gitea role.
#
# NOTE: Either the version must be manually specified (gitea_version) OR the
#       ansible role itself should be updated (make ansible).
#
# Set host_vars according to ansible role.
#
# Ports:
# * gitea_http_port: gitea http service
# * gitea_ssh_port: gitea ssh service
#
# Be sure to update gitea_root_url if setting a proxy.
#
# Reference:
# * https://github.com/roles-ansible/ansible_role_gitea/blob/main/defaults/main.yml
# * https://github.com/roles-ansible/ansible_role_gitea#gitea-version

git_wrapper_packages:
  - 'gnupg2'
  - 'git'
  - 'git-lfs'