---
###############################################################################
# Wireguard Adapter Configuration
###############################################################################
# List of dicts containing wireguard adapters to setup. ALL configuration
# options can be specified dynamically as needed.
#
# Generate keys using wireguard/files/scripts/wggen {HOST}. Store
# vault-encrypted keys in group_vars so both client and server can be
# configured without duplication.
#
# Reference:
# * https://manpages.debian.org/unstable/wireguard-tools/wg.8.en.html
#
# wireguard_adapter_config:
#   - {adapter: {ADAPTER NAME},
#      interface: {Address: {IP/CIDR}, PrivateKey: {VAULT CLIENT PRIVATE}, SaveConfig: 'False'},
#      peers: [
#        {PublicKey: {VAULT SERVER PUBLIC}, EndPoint: { server ip/dns:port }, AllowedIPs: {IP/CIDR}},
#      ]
#     }
#
# Server:
#   wireguard_adapter_config:
#     - {adapter: 'tunnel',
#        interface: {
#          Address: '172.31.255.254/24',
#          SaveConfig: 'False',
#          ListenPort: 51820,
#          PrivateKey: '{{ vault_wireguard_server_private_key }}',
#        },
#        peers: [
#          {PublicKey: '{{ vault_wireguard_client_public_key }}', AllowedIPs: '172.31.255.10/32'},
#        ]
#       }
#
# Client:
#   wireguard_adapter_config:
#     - {adapter: 'tunnel',
#        interface: {
#          Address: '172.31.255.10/24',
#          SaveConfig: 'False',
#          PrivateKey: '{{ vault_wireguard_client_private_key }}',
#        },
#        peers: [
#          {
#            PublicKey: '{{ vault_wireguard_server_public_key }}',
#            AllowedIPs: '172.31.255.254/32',
#            EndPoint: 'wireguard-server.example.com:51820',
#            PersistentKeepalive: 25
#          },
#        ]
#       }

wireguard_adapter_config: []
