---
###############################################################################
# Wireguard-initramfs (wireguard kernel init support) Configuration
###############################################################################
# Wireguard keys and network should be different from the wireguard network
# used on boot, as /boot is generally unencrypted and should be considered
# compromised/untrusted.
#
# Generate keys using wireguard/files/scripts/wggen {HOST}. Store
# vault-encrypted keys in group_vars so both client and server can be
# configured without duplication.
#
# Reference:
# * https://github.com/r-pufky/wireguard-initramfs

# Wireguard interface name.
wireguard_boot_interface: 'example_vpn'

# CIDR wireguard interface address.
wireguard_boot_interface_address: '172.31.255.10/32'

# Peer public key (server's public key). Use vault.
wireguard_boot_peer_public_key: ''

# IP:PORT of the peer (server); any reachable IP/DNS.
wireguard_boot_peer_endpoint: 'wg.example.com:51820'

# Client Private key (client private key). Use vault.
wireguard_boot_client_private_key: ''

# Keepalives. Required to ensure connection for non-exposed ports.
wireguard_boot_persistent_keepalives: '25'

# CIDR IP's allowed on wireguard connection, typically the peer (server).
wireguard_boot_allowed_ips: '172.31.255.254/32'
