---
###############################################################################
# Wireguard Role Configuration
###############################################################################
#
# Reference:
# * https://wireguard.com
# * https://github.com/pirate/wireguard-docs

# Enable wireguard-initramfs. This will allow the use of wireguard during the
# kernel init process (dropbear over wireguard support).
#
# Reference: initramfs.yml
wireguard_initramfs_enable: false

# Enable IP forwarding for wireguard clients. This will enable clients to talk
# to each other if their wireguard configurations allow them to do so.
wireguard_ipv4_forwarding: false
wireguard_ipv6_forwarding: false

# Force refresh adapters. This will remove all existing adapters before
# creating them. If you are connecting to the host over wireguard, this can
# potentially BREAK YOUR CONNECTION. Useful for renaming or removing adapters.
wireguard_force_refresh_adapters: false
