---
###############################################################################
# Ports Configuration
###############################################################################
# Ports should be managed externally via an OS role.
#
# Reference:
# * https://docs.ansible.com/ansible/latest/collections/community/general/ufw_module.html

ports:
  - {proto: 'tcp', from_ip: 'any',       to_port: 8686, direction: 'in', comment: 'lidarr http'}
  - {proto: 'tcp', from_ip: '127.0.0.1', to_port: 8686, direction: 'in', comment: 'lidarr http api'}
  - {proto: 'tcp', from_ip: 'any',       to_port: 6868, direction: 'in', comment: 'lidarr https'}
  - {proto: 'tcp', from_ip: '127.0.0.1', to_port: 6868, direction: 'in', comment: 'lidarr https api'}