---
###############################################################################
# Sphinx Document Generation Build
###############################################################################
# Build sphinx documentation and place in target directory.

- name: 'build | rendering documentation (may take a while)'
  ansible.builtin.debug:
    msg: |
      Sphinx documentation is being rendered. This will take a few minutes.

- name: 'build | generate build commands'
  ansible.builtin.set_fact:
    _sphinx_opts: '"{{ sphinx_source_dir }}" "{{ sphinx_build_dir }}" -j auto -c "{{ sphinx_config_dir }}"'
    _sphinx_command: '{{ sphinx_venv_dir }}/bin/sphinx-build -M '

- name: 'build | link check sphinx documentation (may take a while)'
  ansible.builtin.command: '{{ _sphinx_command }} linkcheck {{ _sphinx_opts }}'
  changed_when: false
  become: true
  become_user: '{{ sphinx_user }}'
  # Reference: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true
  when: sphinx_link_check

- name: 'build | rendering sphinx documentation (may take a while)'
  ansible.builtin.shell: '{{ _sphinx_command }} html {{ _sphinx_opts }}' # for file globbing
  changed_when: false
  become: true
  become_user: '{{ sphinx_user }}'
  # Reference: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true

- name: 'build | copy rendered documentation'
  ansible.posix.synchronize:
    src:       '{{ sphinx_build_dir }}/html/'
    dest:      '{{ sphinx_target_dir }}'
    delete:    true
    recursive: true
    archive:   false
    checksum:  true
  become: true
  become_user: '{{ sphinx_user }}'
  # Reference: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true

- name: 'build | cleanup un-needed documentation files'
  ansible.builtin.file:
    path:  '{{ item }}'
    state: 'absent'
  loop:
    - '{{ sphinx_target_dir }}/objects.inv'
    - '{{ sphinx_target_dir }}/genindex.html'
    - '{{ sphinx_target_dir }}/.buildinfo'
    - '{{ sphinx_target_dir }}/_sources'
